### ISSUE TITLE
I got an error when i run the code. What is the "run_gcn"?

### ISSUE THREAD

**Issue by 00GitHub** [malllabiisc/CompGCN#1]
Hello,
Now I can download the code, but there was an error when I ran the code.So What is the "run_gcn"?I can not find it in the code.
Thank you very much!
![image](https://user-images.githubusercontent.com/22905807/72430601-c881e200-37cd-11ea-8787-5248931d0e9d.png)

**Comment by soumyasanyal** [comment]
Hi 00GitHub,
Thanks for the nice catch! Please go ahead and try running the updated code. The `run_gcn` parameter was initially integrated for some internal optimizations, but we decided to deprecate it in the final version.
