### ISSUE TITLE
Just a small suggestion.

### ISSUE THREAD

**Issue by seankala** [malllabiisc/CompGCN#10]
Hello. This is just a personal suggestion that I had rather than an issue with the code itself.

I think that it may be helpful for future users if you specified in the `README` that users should first create `./log/`, `./data/`, and `./checkpoints/` files before running the code. It's not a big deal, but it would be a bit better user experience IMO.

Thanks.

**Comment by soumyasanyal** [comment]
Please check out the `preprocess.sh` file. We already have those commands as a preprocessing step. We expect new users to follow all the steps mentioned in the `README` before they run the `python` command. We will make this more explicit in the `README`.
