### ISSUE TITLE
The whole graph of the adjacency matrix created with the training set cannot contain some  entities that have not appeared in the training set.

### ISSUE THREAD

**Issue by WeidongLi-KG** [malllabiisc/CompGCN#22]
Therefore, how can you guarantee that the output here gets the embedding vectors of all entities （include the unseen entities in the test or valid set）? 
![image](https://user-images.githubusercontent.com/44043850/100332233-1c736f00-300c-11eb-89ec-97bec9d91db3.png)

Next, your indexing operation may cause problems. 
![image](https://user-images.githubusercontent.com/44043850/100332468-652b2800-300c-11eb-9354-a89b9dd78c4f.png)

These places have caused me a lot of confusion, so I ask for answers.

**Comment by soumyasanyal** [comment]
Hi WeidongLi-KG,

Thanks for your interest in our project. So, if I understand correctly, you mean that our model cannot be used inductively as is for new entities unseen during train time. That is a correct observation. And the reason we don't face issues is the KG link prediction experiments in our paper are in a transductive setting (where all entities are _guaranteed_ to be seen during the train time). Having said that, it should be possible to use our method in an inductive setting as well. Say there is a new node for which we don't know the embedding. But usually, we will be given the edge connections of the new node. We can use the trained CompGCN to get the embedding of the node from its neighborhood. This is a standard procedure in inductive GNN settings. Hope this helps with both your queries!
