### ISSUE TITLE
About cuda version

### ISSUE THREAD

**Issue by yunzi-94** [malllabiisc/CompGCN#23]
In your requirement.txt file, torch==1.4.0, torch_scatter==2.0.4.
I have installed the version as you said, but it goes wrong:

RuntimeError: Detected that PyTorch and torch_scatter were compiled with different CUDA versions. PyTorch has CUDA version 10.1 and torch_scatter has CUDA version 10.2. Please reinstall the torch_scatter that matches your PyTorch install.

**Comment by soumyasanyal** [comment]
Hi @yunzi-94, the torch_scatter library installation process has changed from the time we used it. Please refer to the original repo [link](https://github.com/rusty1s/pytorch_scatter) for details on how to install torch_scatter for the right CUDA version. Specifically, for torch==1.4.0 and CUDA version 10.1 the relevant command should be -
`pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.4.0+cu101.html`
