### ISSUE TITLE
confused about distmult 

### ISSUE THREAD

**Issue by junkangwu** [malllabiisc/CompGCN#25]
According to the model in `distmult` paper, $$score = h_s * M_r * h_o^T$$. However, in the most papers about knowledge graph completion including the model in CompGCN, they are realized as a form of $$score = h_s * r * h_o^T$$. May I ask you about the insight behind your realization form?

**Comment by soumyasanyal** [comment]
Hi @Wjk666 ,

Observe that M_r is a diagonal matrix in DistMult which makes both the forms similar. Typically, I think the authors observed that having a matrix as a relation embedding can be highly overparameterized, hence the diagonalized version was introduced.
[This](https://persagen.com/files/misc/Wang2017Knowledge.pdf) is a good survey to read about the common KG embedding methods which we followed.
