### ISSUE TITLE
Regarding number of GCN updates

### ISSUE THREAD

**Issue by Megh-Thakkar** [malllabiisc/CompGCN#26]
Hi, thank you for the easy-to-understand code repository. As per my understanding, there is only one CompGCN update at every step, which would be similar to aggregating information from the first-hop neighbors. Did you experiment with more hops/iterations?

Thank you.

**Comment by soumyasanyal** [comment]
Yes, we can always add multiple layers of CompGCN to increase the neighborhood influence as required.

**Comment by Megh-Thakkar** [comment]
Thanks for the very quick reply. Just wanted to confirm if it had any effects that you might have experimented with. Closing this for now.

**Comment by soumyasanyal** [comment]
Well, we observed varied benefits of using higher-order neighborhoods for encoding knowledge graphs based on the score function. Usually, 1 layer is quite good but sometimes multiple layers can show better performance. You can check out the commands for the different score functions we have in the Readme, in some of them, we used multiple layers.

**Comment by Megh-Thakkar** [comment]
Got it! Thanks again.
