### ISSUE TITLE
Run with relation basis vectors

### ISSUE THREAD

**Issue by gsp2014** [malllabiisc/CompGCN#6]
Hi, 
Thank you for this wonderful work! I got the following error when I ran with "-num_bases 50" (as suggested in the paper): AttributeError: 'CompGCNConvBasis' object has no attribute 'cache'. Can I just remove Lines 40 and 41 in [compgcn_conv_basis.py](https://github.com/malllabiisc/CompGCN/blob/c5cd749a530f4a24b6be49ec31b201e5a2fc80d0/model/compgcn_conv_basis.py)?

**Comment by soumyasanyal** [comment]
Yes, removing that should work fine, but the cache is useful for the link prediction and node classification tasks where we're operating on the same graph at each iteration. Right now, the code does the norm calculations for each iteration. I've made changes to the file in this [commit](https://github.com/malllabiisc/CompGCN/commit/023cfb0b995f57558f14b20525266b205678c0e2). Feel free to close this after pulling the new changes. Let us know in case of further issues.

**Comment by gsp2014** [comment]
Thank you very much for your prompt reply!
