### ISSUE TITLE
Is 1.1.2 the correct version for `torch-scatter`?

### ISSUE THREAD

**Issue by seankala** [malllabiisc/CompGCN#7]
Hello. I'm just curious if 1.1.2 is the correct version for the `torch-scatter` you're using. I'm asking because I notice that you have a `from torch_scatter import scatter` statement in your `message_passing.py` module, and as far as I'm aware the `scatter` wrapper was not introduced until version 2.0+.

I've tried downloading version 1.1.2 and running your code, but I'm getting a

```
ImportError: cannot import name 'broadcast' from `torch_scatter.utils` (/home/user/anaconda3/envs/userconda/lib/python3.7/site-packages/torch_scatter/utils/__init__.py)
```

I normally don't like opening Git Issues with these kind of problems, but I was hoping perhaps someone would be kind enough to shed some light on my predicament. Thanks!

**Comment by soumyasanyal** [comment]
Thanks for pointing out the issue. Our original code release was compatible with version `1.1.2` of `torch-scatter`. A recent [pull request](https://github.com/malllabiisc/CompGCN/pull/3#issue-379226782) updated the scatter calls but missed the changes to the `requirements.txt`. Please install libraries as per the updated requirements now and reopen the issue if you face further difficulties.
