### ISSUE TITLE
Some questions about the results of W-GCN represented in the paper

### ISSUE THREAD

**Issue by tsaikenyoo** [malllabiisc/CompGCN#8]
Hi, 
thanks for the code. I noticed that in your paper, you represent the results of DistMult + W-GCN in Table 4. But these results are not seen in the paper of W-GCN. I wonder where the results come from. Did you reproduce the results on your own?

Thanks.

**Comment by svjan5** [comment]
Hi @tsaikenyoo,
Yes, we have reproduced those results. W-GCN have provided their code on Github:
https://github.com/JD-AI-Research-Silicon-Valley/SACN
So, we just utilized it for getting those results. 

Thanks and regards,
