### ISSUE TITLE
CompGCN with TransE decoder does not converge

### ISSUE THREAD

**Issue by migalkin** [malllabiisc/CompGCN#9]
Hello dear authors,

thanks for publishing the code!
Trying out different decoders with the default parameters I observe that loss of ConvE and DistMult decoders gradually decreases (and accuracy increases), whereas for the TransE decoder default params do not work and loss/MRR fluctuate around the same point over and over (at least 50+ epochs from start). There are no TransE-specific hyperparams in the paper either, so after varying gcn_layers, gamma (10 to 100), and others, the model still does not converge. 
Could you please provide us with the hyperparams for the TransE decoder?

**Comment by svjan5** [comment]
Hi @migalkin,
Thanks for pointing this out. As far as I remember there are two ways to handle this particular issue. First is that you can start with a lower value of `gamma` (like 9). Another way which gave us slightly better results was that we took `gamma` as 40 initially and whenever the model saturates, we reduce the `gamma` by 5, i.e., 40 -> 35 and like that we tried till the performance stopped improving. 

Let me know if you have any queries about this.

**Comment by migalkin** [comment]
Tried the first option with low `gamma` margins - no luck so far. After the very first batch the loss stabilizes at about 0.008 and MRR is stuck around 0.9% and doesn't change next hundreds of epochs.

**Comment by svjan5** [comment]
Resolved the error. Just pull the code and run it with the given configuration.
